require('setting')
require('plugins')
require('treesitter')
require('lsp')
require('luaLine')
require('null')
require('_telescope')
require('indentation')
-- require('colorSchemes')
require('debuggerDap')
require('_dashboard')
